#!/bin/bash
cd /home/designer

# Run VNC server
export DISPLAY=:1
eval $(vncserver -dry-run) &
echo -e "password\npassword\n" | vncpasswd -u designer -w -r

# Wait for VNC server to start
sleep 1

# Run desktop environment (XFCE)
xfce4-session --display=$DISPLAY

# Keep container alive
sleep infinity
